workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Combine split zip
        script: |
          zip -s 0 yourappname.zip --out full.zip
          unzip full.zip
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
